"use node";

import {
  DetectModerationLabelsCommand,
  RekognitionClient,
  type ModerationLabel,
} from "@aws-sdk/client-rekognition";
import { GetObjectCommand } from "@aws-sdk/client-s3";
import ffmpegStatic from "ffmpeg-static";
import { spawn } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { getS3ClientForRegion, getUploadTargets } from "./media";

export interface ModerationScores {
  nudity: number;
  sexual: number;
  suggestive: number;
  violence: number;
  hate: number;
  spam: number;
  safe: number;
}

export type ModerationTrustTier =
  | "strict"
  | "standard"
  | "trusted"
  | "aggressive";

// ---------------------------------------------------------------------------
// Video reasoning types — structured, timestamped explanations for flagged
// segments. These are stored in the audit and surfaced to the policy layer
// for accurate user-facing messages. They are SEPARATE from the score vector,
// which is unchanged and still drives the block/allow decision.
// ---------------------------------------------------------------------------

export interface VisualContext {
  pose_or_action:
    | "neutral"
    | "aggressive"
    | "suggestive"
    | "explicit"
    | "unknown";
  setting: "indoor" | "outdoor" | "unknown";
  interaction: "none" | "person-to-person" | "object-interaction" | "unknown";
}

export interface FlaggedSegment {
  /** Timestamp of the first flagged frame in this segment (seconds). */
  start_time: number;
  /** Timestamp of the last flagged frame in this segment (seconds). */
  end_time: number;
  /** The primary moderation category that triggered this segment. */
  category: "nudity" | "sexual" | "suggestive" | "violence" | "hate" | "spam";
  /** Confidence score for this specific segment (0–1). */
  confidence: number;
  /** Short human-readable summary of what is visible — never a generic label. */
  summary: string;
  /** Specific visual evidence points: what object/body/action, where in frame, what is absent. */
  detailed_points: string[];
  visual_context: VisualContext;
}

export interface VideoReasoningResult {
  /** Primary category with highest overall confidence across all segments. */
  primary_label:
    | "nudity"
    | "sexual"
    | "suggestive"
    | "violence"
    | "hate"
    | "spam"
    | "safe";
  /** Overall confidence for the primary label (0–1). */
  confidence: number;
  /** Severity of the primary violation. */
  severity: "low" | "medium" | "high";
  /** All flagged time segments with specific evidence. */
  flagged_segments: FlaggedSegment[];
  /** Uncertainty notes — populated when confidence < 0.9. */
  uncertainty_notes: string[];
  /** Recommended moderation action based on segment evidence. */
  decision: "allow" | "flag_for_review" | "restrict" | "remove";
  /** Whether this reasoning was generated by Gemini or synthesised from scores. */
  source: "gemini_reasoning" | "score_synthesis";
}

export interface VideoModerationAudit {
  mediaIndex: number;
  frameCountRequested: number;
  framesAnalyzed: number;
  frameScores: Array<
    ModerationScores & {
      frameIndex: number;
      timestampSec: number;
      provider: string;
      reason?: string;
      detectedLabels?: string[];
      userSummary?: string;
      reasonInternal?: string;
    }
  >;
  audioTranscript?: string;
  audioScores?: ModerationScores;
  provider: string;
  usedRekognition: boolean;
  failures: string[];
  durationMs: number;
  /** Structured reasoning output. Present when at least one frame exceeded a flag threshold. */
  reasoning?: VideoReasoningResult;
}

export interface VideoModerationResult {
  scores: ModerationScores;
  audit: VideoModerationAudit;
  mediaHash?: string;
  classificationFailed: boolean;
  safetyBlocked: boolean;
  safetyBlockReason?: string;
  safetyBlockCategory?: string;
  /** All detected object/context labels across frames (deduplicated). */
  detectedLabels: string[];
  /** Best AI-provided plain-English reason from any frame. */
  aiReason?: string;
  /** Structured reasoning output — present when content was flagged. */
  reasoning?: VideoReasoningResult;
}

type ParsedModeration = ModerationScores & {
  bodyPartFocus?: boolean;
  highSkinRatio?: boolean;
  detectedLabels?: string[];
  reason?: string;
  userSummary?: string;
  reasonInternal?: string;
  primaryCategory?: string;
  evidence?: string[];
  severity?: string;
  confidence?: number;
};

type GeminiModerationResult = {
  scores: ParsedModeration;
  reason?: string;
  detectedLabels?: string[];
  userSummary?: string;
  reasonInternal?: string;
  classificationFailed: boolean;
  safetyBlocked: boolean;
  safetyBlockReason?: string;
  safetyBlockCategory?: string;
};

type ExtractedFrame = {
  path: string;
  timestampSec: number;
  index: number;
};

const GEMINI_MODEL = "gemini-2.5-flash";
const EMPTY_SCORES: ModerationScores = {
  nudity: 0,
  sexual: 0,
  suggestive: 0,
  violence: 0,
  hate: 0,
  spam: 0,
  safe: 0.5,
};

/**
 * FAIL-SAFE: when parsing or provider calls fail, we do NOT flag the content.
 * Flagging innocent content due to system errors is worse than missing a rare
 * violation. The content stays in "allow" state and can be re-checked later.
 */
const SAFE_PASS_SCORES: ModerationScores = {
  nudity: 0,
  sexual: 0,
  suggestive: 0,
  violence: 0,
  hate: 0,
  spam: 0,
  safe: 1,
};

const IMAGE_MODERATION_PROMPT = `Analyze this frame from a video for safety moderation.

Return VALID JSON ONLY.

Detect ALL categories with confidence (0–1):
- violence
- gore
- weapons
- nudity
- sexual_content
- self_harm
- harassment

Then:
1. Select ONE primary_category based on highest severity + confidence
2. Provide confidence (0–1)
3. Provide severity: low | medium | high
4. Provide explanation describing EXACTLY what is visible
5. Provide evidence[] with literal observations
6. Describe what is happening, the setting, objects visible, human activity, and inferred context

Rules:
- No generic statements
- No disclaimers
- No guessing
- Be specific and useful for content understanding
- If nothing unsafe → primary_category = null

Output:

{
  "categories": {
    "violence": 0.0,
    "gore": 0.0,
    "weapons": 0.0,
    "nudity": 0.0,
    "sexual_content": 0.0,
    "self_harm": 0.0,
    "harassment": 0.0
  },
  "primary_category": "...",
  "confidence": 0.0,
  "severity": "low|medium|high",
  "explanation": "...",
  "evidence": ["...", "..."],
  "scene_description": {
    "activity": "what is happening",
    "setting": "indoor/outdoor/specific location",
    "objects": ["visible objects"],
    "human_activity": "what people are doing",
    "inferred_context": "broader context of the scene"
  }
}`;

const TEXT_MODERATION_PROMPT = `Analyze this text for safety moderation.

Return VALID JSON ONLY.

Detect ALL categories with confidence (0–1):
- violence
- gore
- weapons
- nudity
- sexual_content
- self_harm
- harassment

Then:
1. Select ONE primary_category based on highest severity + confidence
2. Provide confidence (0–1)
3. Provide severity: low | medium | high
4. Provide explanation describing EXACTLY what is present
5. Provide evidence[] with literal observations

Rules:
- No generic statements
- No disclaimers
- No guessing
- If nothing unsafe → primary_category = null

Output:

{
  "categories": {
    "violence": 0.0,
    "gore": 0.0,
    "weapons": 0.0,
    "nudity": 0.0,
    "sexual_content": 0.0,
    "self_harm": 0.0,
    "harassment": 0.0
  },
  "primary_category": "...",
  "confidence": 0.0,
  "severity": "low|medium|high",
  "explanation": "...",
  "evidence": ["...", "..."]
}

Text to analyze:
`;

const AUDIO_TRANSCRIPTION_PROMPT =
  "Transcribe this audio accurately. Return only the spoken words. If there is no understandable speech, return an empty string.";

function clampScore(n: unknown): number {
  if (typeof n === "number" && Number.isFinite(n))
    return Math.max(0, Math.min(1, n));
  if (typeof n === "string") {
    const v = Number(n.trim());
    if (Number.isFinite(v)) return Math.max(0, Math.min(1, v));
  }
  return 0;
}

function sanitizeModerationTextField(
  raw: unknown,
  maxLen: number,
): string | undefined {
  if (typeof raw !== "string") return undefined;
  const flattened = raw.replace(/\s+/g, " ").replace(/[<>]/g, "").trim();
  if (
    !flattened ||
    /^none\.?$/i.test(flattened) ||
    /^safe\.?$/i.test(flattened)
  )
    return undefined;
  /** Never bubble raw floats that look like model scores through to humans. */
  if (/\b0\.\d{2,}\b/.test(flattened)) return undefined;
  return flattened.replace(/[.。]+$/, "").slice(0, maxLen);
}

function sanitizeAiReason(raw: unknown): string | undefined {
  return sanitizeModerationTextField(raw, 220);
}

function sanitizeInternalModerationNotes(raw: unknown): string | undefined {
  return sanitizeModerationTextField(raw, 4000);
}

function sanitizeUserSummary(raw: unknown): string | undefined {
  return sanitizeModerationTextField(raw, 620);
}

function parseDetectedLabels(raw: unknown): string[] {
  if (!Array.isArray(raw)) return [];
  return raw
    .filter((v): v is string => typeof v === "string" && v.trim().length > 0)
    .map((v) => v.trim().toLowerCase());
}

/**
 * Context-aware adjustments:
 * - Violence labels: prevent blood-on-skin from being scored as nudity.
 * - Nature / waterfalls: damp nudity & suggestive scores when there's no human subject cue.
 */
function applyContextSignals(
  scores: ParsedModeration,
  labels: string[],
): ParsedModeration {
  const VIOLENCE_OBJECTS = [
    "knife",
    "weapon",
    "gun",
    "pistol",
    "rifle",
    "sword",
    "blood",
    "injury",
    "wound",
    "fight",
    "fighting",
    "punch",
    "kick",
    "stab",
    "stabbing",
    "gore",
    "corpse",
    "dead",
    "shooting",
  ];
  const SKIN_FALSE_POS = ["blood", "wound", "injury", "bruise", "cut", "stab"];

  const NATURE_SCENE = [
    "waterfall",
    "waterfalls",
    "mist",
    "misty",
    "spray",
    "cascade",
    "rapid",
    "rapids",
    "river",
    "stream",
    "ocean",
    "wave",
    "waves",
    "surf",
    "sand",
    "rock",
    "rocks",
    "stone",
    "cliff",
    "mountain",
    "forest",
    "trees",
    "vegetation",
    "landscape",
    "lake",
    "rainbow",
    "snowfield",
    "glacier",
  ];

  let adj = { ...scores };

  const hasViolenceObject = labels.some((l) =>
    VIOLENCE_OBJECTS.some((v) => l.includes(v)),
  );
  const hasSkinFalsePositive = labels.some((l) =>
    SKIN_FALSE_POS.some((v) => l.includes(v)),
  );

  if (hasViolenceObject) {
    adj.violence = Math.min(1, adj.violence + 0.15);
  }
  if (hasViolenceObject || hasSkinFalsePositive) {
    if (hasSkinFalsePositive && adj.violence > adj.nudity * 0.6) {
      const reductionFactor = 0.55;
      adj.nudity = Math.max(0, adj.nudity * reductionFactor);
      adj.sexual = Math.max(0, adj.sexual * reductionFactor);
      adj.suggestive = Math.max(0, adj.suggestive * reductionFactor);
    }
  }

  const labelBlob = labels.join(",").toLowerCase();
  const hasNatureScene = labels.some((l) =>
    NATURE_SCENE.some((w) => l.includes(w)),
  );
  const hasPersonCue =
    /\b(person|people|human|humans|portrait|faces?|woman|women|girl|girls|man|men|boy|boys|child|children|infants?|shirtless|selfie)\b/i.test(
      labelBlob,
    );

  if (hasNatureScene && !hasPersonCue) {
    const nudCap = 0.2;
    const sexCap = 0.22;
    const sugCap = 0.28;
    if (adj.nudity > nudCap) adj.nudity = nudCap;
    if (adj.sexual > sexCap) adj.sexual = sexCap;
    if (adj.suggestive > sugCap) adj.suggestive = sugCap;
  }

  adj.safe =
    1 -
    Math.max(adj.nudity, adj.sexual, adj.suggestive, adj.violence, adj.hate);
  return adj;
}

/** Normalize a MIME type string to one Gemini accepts for inline image data. */
function normalizeImageMime(mime: string): "image/jpeg" | "image/png" {
  const m = (mime ?? "").toLowerCase().split(";")[0].trim();
  if (m === "image/png") return "image/png";
  // Accept jpeg, jpg, webp, gif, bmp — all converted to jpeg label since
  // ffmpeg always emits JPEG frames and S3 headers may vary.
  return "image/jpeg";
}

/**
 * Validate and clean a base64 string before it is sent to Gemini.
 * Strips the data-URL prefix if present and rejects strings that are too
 * small to represent a real image (empty, whitespace, or stub data).
 * Throws if the input cannot be made safe.
 */
function validateAndCleanBase64(base64: string, context: string): string {
  if (!base64) throw new Error(`[${context}] Missing base64 data`);

  let clean = base64;
  if (clean.startsWith("data:")) {
    clean = clean.replace(/^data:[^;]+;base64,/, "");
  }
  clean = clean.trim();

  if (clean.length < 1_000) {
    throw new Error(
      `[${context}] Base64 too small (${clean.length} chars) — likely invalid frame`,
    );
  }

  return clean;
}

function parseSeverityVm(raw: unknown): string | undefined {
  if (typeof raw !== "string") return undefined;
  const v = raw.trim().toLowerCase();
  if (v === "low" || v === "medium" || v === "high") return v;
  return undefined;
}

function parseEvidenceArrayVm(raw: unknown): string[] | undefined {
  if (!Array.isArray(raw)) return undefined;
  const items = raw
    .filter((x): x is string => typeof x === "string")
    .map((s) => s.replace(/\s+/g, " ").replace(/[<>]/g, "").trim())
    .filter((s) => s.length > 2 && s.length < 300);
  return items.length > 0 ? items.slice(0, 5) : undefined;
}

function scoresFromParsedRecord(
  parsed: Record<string, unknown>,
): ParsedModeration {
  const detectedLabels = parseDetectedLabels(parsed.detectedLabels);
  const internalRaw =
    parsed.reasonInternal ??
    parsed.internalExplanation ??
    parsed.internalNotes ??
    parsed.moderatorNotes;

  const primaryCategoryRaw = parsed.primary_category ?? parsed.primaryCategory;
  const confidenceRaw = parsed.confidence;
  const severityRaw = parsed.severity;
  const evidenceRaw = parsed.evidence;

  const categoriesObj = parsed.categories as
    | Record<string, unknown>
    | undefined;

  const base: ParsedModeration = {
    nudity: clampScore(categoriesObj?.nudity ?? parsed.nudity),
    sexual: clampScore(categoriesObj?.sexual_content ?? parsed.sexual),
    suggestive: clampScore(parsed.suggestive),
    violence: Math.max(
      clampScore(categoriesObj?.violence ?? parsed.violence),
      clampScore(categoriesObj?.gore ?? 0),
      clampScore(categoriesObj?.weapons ?? 0),
    ),
    hate: clampScore(categoriesObj?.harassment ?? parsed.hate),
    spam: clampScore(parsed.spam),
    safe: clampScore(parsed.safe),
    bodyPartFocus: parsed.bodyPartFocus === true,
    highSkinRatio: parsed.highSkinRatio === true,
    detectedLabels,
    reason: sanitizeAiReason(parsed.reason ?? parsed.explanation),
    userSummary: sanitizeUserSummary(
      parsed.userSummary ?? parsed.authorSummary ?? parsed.summaryForAuthor,
    ),
    reasonInternal: sanitizeInternalModerationNotes(internalRaw),
    primaryCategory:
      typeof primaryCategoryRaw === "string"
        ? primaryCategoryRaw.trim().toLowerCase() === "none" ||
          primaryCategoryRaw.trim() === ""
          ? undefined
          : primaryCategoryRaw.trim().toLowerCase()
        : undefined,
    evidence: parseEvidenceArrayVm(evidenceRaw),
    severity: parseSeverityVm(severityRaw),
    confidence:
      typeof confidenceRaw === "number" && Number.isFinite(confidenceRaw)
        ? Math.max(0, Math.min(1, confidenceRaw))
        : undefined,
  };

  if (
    base.safe === 0 &&
    base.nudity === 0 &&
    base.sexual === 0 &&
    base.violence === 0 &&
    base.hate === 0
  ) {
    base.safe = 1;
  }

  return applyContextSignals(base, detectedLabels);
}

function parseModerationJson(raw: string): {
  scores: ParsedModeration;
  failed: boolean;
} {
  const cleaned = raw
    .replace(/^\uFEFF/, "")
    .replace(/```json\s*/gi, "")
    .replace(/```\s*/g, "")
    .trim();
  const match = cleaned.startsWith("{")
    ? cleaned
    : cleaned.match(/\{[\s\S]*\}/)?.[0];
  if (!match) return { scores: { ...SAFE_PASS_SCORES }, failed: true };
  try {
    const parsed = JSON.parse(match) as Record<string, unknown>;

    const primaryCategoryRaw =
      parsed.primary_category ?? parsed.primaryCategory;
    if (
      !primaryCategoryRaw ||
      primaryCategoryRaw === "null" ||
      primaryCategoryRaw === "none"
    ) {
      return { scores: { ...EMPTY_SCORES, safe: 1 }, failed: false };
    }

    if (!Array.isArray(parsed.evidence)) {
      return { scores: { ...EMPTY_SCORES, safe: 1 }, failed: false };
    }

    const scores = scoresFromParsedRecord(parsed);
    return { scores, failed: false };
  } catch {
    return { scores: { ...SAFE_PASS_SCORES }, failed: true };
  }
}

function extractGeminiText(data: unknown): string {
  const d = data as {
    candidates?: Array<{
      content?: { parts?: Array<{ text?: string; thought?: boolean }> };
    }>;
  };
  const parts = d?.candidates?.[0]?.content?.parts ?? [];
  return parts
    .filter((p) => p?.thought !== true)
    .map((p) => p?.text ?? "")
    .join("")
    .trim();
}

function geminiSafetyBlock(data: unknown): {
  blocked: boolean;
  reason?: string;
  category?: string;
} {
  const d = data as {
    promptFeedback?: {
      blockReason?: string;
      safetyRatings?: Array<{ category?: string; blocked?: boolean }>;
    };
    candidates?: Array<{
      finishReason?: string;
      safetyRatings?: Array<{ category?: string; blocked?: boolean }>;
    }>;
  };
  if (d?.promptFeedback?.blockReason) {
    return {
      blocked: true,
      reason: d.promptFeedback.blockReason,
      category: d.promptFeedback.safetyRatings?.find((r) => r.blocked)
        ?.category,
    };
  }
  const cand = d?.candidates?.[0];
  if (
    cand?.finishReason === "SAFETY" ||
    cand?.finishReason === "RECITATION" ||
    cand?.finishReason === "PROHIBITED_CONTENT"
  ) {
    return {
      blocked: true,
      reason: cand.finishReason,
      category: cand.safetyRatings?.find((r) => r.blocked)?.category,
    };
  }
  return { blocked: false };
}

async function callGemini(
  apiKey: string,
  parts: Array<Record<string, unknown>>,
  responseMimeType?: "application/json",
): Promise<{
  text: string;
  safetyBlocked: boolean;
  safetyBlockReason?: string;
  safetyBlockCategory?: string;
}> {
  // Guard: always include at least one text part to avoid Gemini 400 errors.
  const hasText = parts.some((p) => typeof p.text === "string" && p.text.length > 0);
  const safeParts = hasText
    ? parts
    : [
        ...parts,
        { text: "Analyze this frame from a video and describe context, setting, and activity." },
      ];
  const url = `https://generativelanguage.googleapis.com/v1/models/${GEMINI_MODEL}:generateContent?key=${apiKey}`;
  const resp = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      contents: [{ parts: safeParts }],
      generationConfig: {
        temperature: 0.1,
        maxOutputTokens: responseMimeType ? 4096 : 8192,
        ...(responseMimeType ? { responseMimeType } : {}),
      },
      safetySettings: [
        { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_NONE" },
        { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_NONE" },
        {
          category: "HARM_CATEGORY_SEXUALLY_EXPLICIT",
          threshold: "BLOCK_NONE",
        },
        {
          category: "HARM_CATEGORY_DANGEROUS_CONTENT",
          threshold: "BLOCK_NONE",
        },
        { category: "HARM_CATEGORY_CIVIC_INTEGRITY", threshold: "BLOCK_NONE" },
      ],
    }),
  });
  if (!resp.ok) {
    const errText = await resp.text().catch(() => "unknown");
    throw new Error(`Gemini API ${resp.status}: ${errText}`);
  }
  const data = await resp.json();
  const safety = geminiSafetyBlock(data);
  return {
    text: extractGeminiText(data),
    safetyBlocked: safety.blocked,
    safetyBlockReason: safety.reason,
    safetyBlockCategory: safety.category,
  };
}

async function moderateImageBase64(
  apiKey: string,
  base64: string,
  mime = "image/jpeg",
): Promise<GeminiModerationResult> {
  const safeMime = normalizeImageMime(mime);
  let cleanBase64: string;
  try {
    cleanBase64 = validateAndCleanBase64(base64, "moderateImageBase64");
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error("[VideoModeration] base64 validation failed:", msg);
    return {
      scores: { ...SAFE_PASS_SCORES },
      classificationFailed: true,
      safetyBlocked: false,
    };
  }

  console.log("[VideoModeration] Gemini image request", {
    mimeType: safeMime,
    base64Length: cleanBase64.length,
    approxBytes: Math.round(cleanBase64.length * 0.75),
    startsWithDataPrefix: base64.startsWith("data:"),
  });

  const out = await callGemini(
    apiKey,
    [
      { text: IMAGE_MODERATION_PROMPT },
      { inlineData: { mimeType: safeMime, data: cleanBase64 } },
    ],
    "application/json",
  );
  if (out.safetyBlocked) {
    return {
      scores: { ...SAFE_PASS_SCORES },
      classificationFailed: true,
      safetyBlocked: true,
      safetyBlockReason: out.safetyBlockReason,
      safetyBlockCategory: out.safetyBlockCategory,
    };
  }
  const parsed = parseModerationJson(out.text);
  return {
    scores: parsed.scores,
    reason: parsed.scores.reason,
    detectedLabels: parsed.scores.detectedLabels,
    userSummary: parsed.scores.userSummary,
    reasonInternal: parsed.scores.reasonInternal,
    classificationFailed: parsed.failed,
    safetyBlocked: false,
  };
}

async function moderateText(
  apiKey: string,
  text: string,
): Promise<GeminiModerationResult> {
  if (!text.trim()) {
    return {
      scores: { ...EMPTY_SCORES },
      classificationFailed: false,
      safetyBlocked: false,
    };
  }
  const out = await callGemini(
    apiKey,
    [{ text: TEXT_MODERATION_PROMPT + text }],
    "application/json",
  );
  if (out.safetyBlocked) {
    return {
      scores: { ...SAFE_PASS_SCORES },
      classificationFailed: true,
      safetyBlocked: true,
      safetyBlockReason: out.safetyBlockReason,
      safetyBlockCategory: out.safetyBlockCategory,
    };
  }
  const parsed = parseModerationJson(out.text);
  return {
    scores: parsed.scores,
    reason: parsed.scores.reason,
    detectedLabels: parsed.scores.detectedLabels,
    userSummary: parsed.scores.userSummary,
    reasonInternal: parsed.scores.reasonInternal,
    classificationFailed: parsed.failed,
    safetyBlocked: false,
  };
}

function rekognitionRegion(): string {
  return (
    process.env.AWS_REKOGNITION_REGION ||
    process.env.AWS_DEFAULT_REGION ||
    "us-east-1"
  );
}

let rekognitionClient: RekognitionClient | null = null;
function getRekognitionClient(): RekognitionClient | null {
  const id = process.env.AWS_ACCESS_KEY_ID;
  const secret = process.env.AWS_SECRET_ACCESS_KEY;
  if (!id || !secret) return null;
  if (!rekognitionClient) {
    rekognitionClient = new RekognitionClient({
      region: rekognitionRegion(),
      credentials: { accessKeyId: id, secretAccessKey: secret },
    });
  }
  return rekognitionClient;
}

function mapRekognition(labels: ModerationLabel[]): ModerationScores {
  let nudity = 0;
  let sexual = 0;
  let suggestive = 0;
  let violence = 0;
  let hate = 0;
  for (const label of labels) {
    const name = (label.Name ?? "").toLowerCase();
    const parent = (label.ParentName ?? "").toLowerCase();
    const conf = (label.Confidence ?? 0) / 100;
    if (!conf) continue;
    if (
      name.includes("explicit nudity") ||
      name.includes("genitalia") ||
      name.includes("exposed breast") ||
      name.includes("exposed buttocks")
    ) {
      nudity = Math.max(nudity, conf);
      sexual = Math.max(sexual, conf * 0.9);
    }
    if (name.includes("sexual activity") || name.includes("sex toys")) {
      sexual = Math.max(sexual, conf);
    }
    if (
      parent === "suggestive" ||
      name.includes("lingerie") ||
      name.includes("implied nudity") ||
      name.includes("partial nudity")
    ) {
      suggestive = Math.max(suggestive, conf);
    }
    if (
      parent === "violence" ||
      name.includes("gore") ||
      name.includes("weapon")
    ) {
      violence = Math.max(violence, conf);
    }
    if (
      parent === "hate symbols" ||
      name.includes("nazi") ||
      name.includes("extremist")
    ) {
      hate = Math.max(hate, conf);
    }
  }
  return {
    nudity,
    sexual,
    suggestive,
    violence,
    hate,
    spam: 0,
    safe: 1 - Math.max(nudity, sexual, suggestive, violence, hate),
  };
}

async function moderateWithRekognition(
  bytes: Buffer,
): Promise<ModerationScores> {
  const client = getRekognitionClient();
  if (!client)
    throw new Error("AWS credentials missing for Rekognition fallback");
  const out = await client.send(
    new DetectModerationLabelsCommand({
      Image: { Bytes: bytes },
      MinConfidence: 50,
    }),
  );
  return mapRekognition(out.ModerationLabels ?? []);
}

export function mergeScores(scores: ModerationScores[]): ModerationScores {
  if (scores.length === 0) return { ...SAFE_PASS_SCORES };
  return scores.reduce<ModerationScores>(
    (acc, s) => ({
      nudity: Math.max(acc.nudity, s.nudity),
      sexual: Math.max(acc.sexual, s.sexual),
      suggestive: Math.max(acc.suggestive, s.suggestive),
      violence: Math.max(acc.violence, s.violence),
      hate: Math.max(acc.hate, s.hate),
      spam: Math.max(acc.spam, s.spam),
      safe: Math.min(acc.safe, s.safe),
    }),
    {
      nudity: 0,
      sexual: 0,
      suggestive: 0,
      violence: 0,
      hate: 0,
      spam: 0,
      safe: 1,
    },
  );
}

function sampleCount(
  durationSec: number | undefined,
  _trustTier: ModerationTrustTier,
): number {
  const d = durationSec && durationSec > 0 ? durationSec : 10;
  if (d > 60) return 3;
  return 4;
}

function sampleTimestamps(
  durationSec: number | undefined,
  count: number,
): number[] {
  const d = durationSec && durationSec > 0 ? durationSec : 10;
  const pcts =
    d > 60 ? [0.1, 0.3, 0.5] : [0.1, 0.3, 0.5, 0.7, 0.9];
  return pcts.slice(0, count).map((p) => Math.max(0.5, d * p));
}

function ffmpegBin(): string {
  if (!ffmpegStatic) throw new Error("ffmpeg-static did not resolve a binary");
  return ffmpegStatic;
}

async function runFfmpeg(args: string[], timeoutMs: number): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    const child = spawn(ffmpegBin(), args, {
      stdio: ["ignore", "ignore", "pipe"],
    });
    let err = "";
    const timer = setTimeout(() => {
      child.kill("SIGKILL");
      reject(new Error(`ffmpeg timed out after ${timeoutMs}ms`));
    }, timeoutMs);
    child.stderr.on("data", (chunk) => {
      err += String(chunk).slice(0, 2000);
    });
    child.on("error", (e) => {
      clearTimeout(timer);
      reject(e);
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      if (code === 0) resolve();
      else reject(new Error(`ffmpeg exited ${code}: ${err.slice(-1200)}`));
    });
  });
}

/** Validate that a buffer starts and ends with the JPEG magic bytes. */
function isValidJpeg(buf: Buffer): boolean {
  return (
    buf.length >= 4 &&
    buf[0] === 0xff &&
    buf[1] === 0xd8 &&
    buf[buf.length - 2] === 0xff &&
    buf[buf.length - 1] === 0xd9
  );
}

/**
 * Extract a single JPEG frame from `videoPath` at `timestampSec` into `outPath`.
 *
 * Uses `-skip_frame nokey` so FFmpeg only decodes keyframes — this prevents
 * corrupt / black / half-decoded frames that arise when a timestamp falls on a
 * B-frame or P-frame deep inside a long-GOP segment.
 *
 * Returns `true` when a valid JPEG was written, `false` otherwise.
 */
async function extractSingleFrame(
  videoPath: string,
  timestampSec: number,
  outPath: string,
): Promise<boolean> {
  try {
    await runFfmpeg(
      [
        "-y",
        "-skip_frame",
        "nokey",
        "-ss",
        timestampSec.toFixed(3),
        "-i",
        videoPath,
        "-frames:v",
        "1",
        "-vf",
        "scale=512:-1",
        "-q:v",
        "5",
        "-f",
        "image2",
        outPath,
      ],
      20_000,
    );
  } catch (err) {
    console.warn("[VideoModeration] FFmpeg frame extraction error", {
      timestamp: timestampSec,
      error: err instanceof Error ? err.message : String(err),
    });
    return false;
  }

  // Confirm the file was written and contains a valid JPEG.
  try {
    const buf = await readFile(outPath);
    if (buf.length < 10_000 || !isValidJpeg(buf)) {
      console.warn(
        "[VideoModeration] Frame invalid or empty after extraction",
        {
          timestamp: timestampSec,
          byteLength: buf.length,
          headerOk: buf.length >= 2 && buf[0] === 0xff && buf[1] === 0xd8,
        },
      );
      return false;
    }
    return true;
  } catch {
    return false;
  }
}

export async function extractFramesFromVideo(args: {
  videoPath: string;
  workDir: string;
  durationSec?: number;
  trustTier: ModerationTrustTier;
}): Promise<ExtractedFrame[]> {
  const timestamps = sampleTimestamps(
    args.durationSec,
    sampleCount(args.durationSec, args.trustTier),
  );
  const frames: ExtractedFrame[] = [];

  for (let i = 0; i < timestamps.length; i++) {
    const base = join(args.workDir, `frame-${String(i).padStart(2, "0")}.jpg`);

    // Try up to 3 times with a 0.5 s forward offset on each retry.  This
    // recovers from timestamps that land between keyframes on long-GOP video.
    let succeeded = false;
    for (let attempt = 0; attempt < 3; attempt++) {
      const ts = timestamps[i] + attempt * 0.5;
      const ok = await extractSingleFrame(args.videoPath, ts, base);
      if (ok) {
        frames.push({ path: base, timestampSec: ts, index: i });
        succeeded = true;
        break;
      }
      console.warn("[VideoModeration] Frame attempt failed, retrying", {
        frameIndex: i,
        attempt,
        timestamp: ts,
      });
    }

    if (!succeeded) {
      console.warn(
        "[VideoModeration] All attempts failed for frame, skipping",
        { frameIndex: i, baseTimestamp: timestamps[i] },
      );
    }
  }

  return frames;
}

export async function moderateFrame(args: {
  apiKey: string;
  framePath: string;
  frameIndex: number;
  timestampSec: number;
}): Promise<
  ModerationScores & {
    frameIndex: number;
    timestampSec: number;
    provider: string;
    reason?: string;
    detectedLabels?: string[];
    userSummary?: string;
    reasonInternal?: string;
    classificationFailed?: boolean;
    safetyBlocked?: boolean;
    safetyBlockReason?: string;
    safetyBlockCategory?: string;
  }
> {
  // Guard 1: file must exist and be large enough to be a real JPEG.
  let fileSize = 0;
  try {
    const s = await stat(args.framePath);
    fileSize = s.size;
  } catch {
    console.warn("[VideoModeration] Frame file missing, skipping", {
      framePath: args.framePath,
      frameIndex: args.frameIndex,
    });
    return {
      ...SAFE_PASS_SCORES,
      frameIndex: args.frameIndex,
      timestampSec: args.timestampSec,
      provider: "fail_safe",
      classificationFailed: true,
      reason: "analysis_failed_safe_fallback",
    };
  }

  if (fileSize < 10_000) {
    console.warn("[VideoModeration] Frame too small, skipping Gemini", {
      framePath: args.framePath,
      frameIndex: args.frameIndex,
      byteLength: fileSize,
    });
    return {
      ...SAFE_PASS_SCORES,
      frameIndex: args.frameIndex,
      timestampSec: args.timestampSec,
      provider: "fail_safe",
      classificationFailed: true,
      reason: "analysis_failed_safe_fallback",
    };
  }

  const bytes = await readFile(args.framePath);

  // Guard 2: double-check buffer length and JPEG integrity after read.
  if (bytes.length < 10_000 || !isValidJpeg(bytes)) {
    console.warn(
      "[VideoModeration] Frame buffer invalid after read, skipping",
      {
        framePath: args.framePath,
        frameIndex: args.frameIndex,
        byteLength: bytes.length,
        headerOk: bytes.length >= 2 && bytes[0] === 0xff && bytes[1] === 0xd8,
        footerOk:
          bytes.length >= 2 &&
          bytes[bytes.length - 2] === 0xff &&
          bytes[bytes.length - 1] === 0xd9,
      },
    );
    return {
      ...SAFE_PASS_SCORES,
      frameIndex: args.frameIndex,
      timestampSec: args.timestampSec,
      provider: "fail_safe",
      classificationFailed: true,
      reason: "analysis_failed_safe_fallback",
    };
  }

  // Guard 2b: reject frames that are unreasonably large for Gemini inline data.
  if (bytes.length > 1_000_000) {
    console.warn("[VideoModeration] Frame buffer too large, skipping Gemini", {
      framePath: args.framePath,
      frameIndex: args.frameIndex,
      byteLength: bytes.length,
    });
    return {
      ...SAFE_PASS_SCORES,
      frameIndex: args.frameIndex,
      timestampSec: args.timestampSec,
      provider: "fail_safe",
      classificationFailed: true,
      reason: "analysis_failed_safe_fallback",
    };
  }

  const base64 = bytes.toString("base64");
  const cleanBase64 = base64.replace(/^data:image\/\w+;base64,/, "");

  // Guard 3: base64 string must be long enough to represent real image data.
  if (!cleanBase64 || cleanBase64.length < 1_000) {
    console.warn("[VideoModeration] Frame base64 too short, skipping Gemini", {
      framePath: args.framePath,
      frameIndex: args.frameIndex,
      base64Length: cleanBase64?.length ?? 0,
    });
    return {
      ...SAFE_PASS_SCORES,
      frameIndex: args.frameIndex,
      timestampSec: args.timestampSec,
      provider: "fail_safe",
      classificationFailed: true,
      reason: "analysis_failed_safe_fallback",
    };
  }

  console.log("FRAME DEBUG", {
    frameIndex: args.frameIndex,
    timestampSec: args.timestampSec,
    path: args.framePath,
    size: bytes.length,
    base64Length: cleanBase64.length,
    preview: cleanBase64.slice(0, 40),
  });

  try {
    const gemini = await moderateImageBase64(
      args.apiKey,
      cleanBase64,
      "image/jpeg",
    );
    if (gemini.safetyBlocked) {
      console.warn("[VideoModeration] Frame safety-blocked by Gemini", {
        frameIndex: args.frameIndex,
        safetyBlockReason: gemini.safetyBlockReason,
      });
      return {
        ...SAFE_PASS_SCORES,
        frameIndex: args.frameIndex,
        timestampSec: args.timestampSec,
        provider: "gemini_safety_blocked",
        safetyBlocked: true,
        safetyBlockReason: gemini.safetyBlockReason,
        safetyBlockCategory: gemini.safetyBlockCategory,
        classificationFailed: true,
      };
    }
    if (gemini.classificationFailed) {
      console.warn("[VideoModeration] Frame classification failed", {
        frameIndex: args.frameIndex,
      });
      return {
        ...SAFE_PASS_SCORES,
        frameIndex: args.frameIndex,
        timestampSec: args.timestampSec,
        provider: "fail_safe",
        reason: "analysis_failed_safe_fallback",
        classificationFailed: true,
      };
    }
    return {
      ...gemini.scores,
      frameIndex: args.frameIndex,
      timestampSec: args.timestampSec,
      provider: "gemini",
      reason: gemini.reason,
      detectedLabels: gemini.detectedLabels,
      userSummary: gemini.scores.userSummary,
      reasonInternal: gemini.scores.reasonInternal,
    };
  } catch (err: any) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error("GEMINI FRAME ERROR", {
      path: args.framePath,
      frameIndex: args.frameIndex,
      size: bytes?.length,
      base64Length: cleanBase64?.length,
      error: err?.response?.data || msg,
    });
    return {
      ...SAFE_PASS_SCORES,
      frameIndex: args.frameIndex,
      timestampSec: args.timestampSec,
      provider: "fail_safe",
      reason: "analysis_failed_safe_fallback",
      classificationFailed: true,
    };
  }
}

async function extractAudio(
  videoPath: string,
  outputPath: string,
): Promise<void> {
  await runFfmpeg(
    [
      "-y",
      "-i",
      videoPath,
      "-vn",
      "-ac",
      "1",
      "-ar",
      "16000",
      "-t",
      "180",
      "-f",
      "mp3",
      outputPath,
    ],
    45_000,
  );
}

export async function moderateAudio(args: {
  apiKey: string;
  videoPath: string;
  workDir: string;
  hasAudioTrack?: boolean;
}): Promise<{
  scores: ModerationScores;
  transcript?: string;
  skipped: boolean;
}> {
  if (args.hasAudioTrack === false) {
    return { scores: { ...EMPTY_SCORES, safe: 1 }, skipped: true };
  }
  const audioPath = join(args.workDir, "audio.mp3");
  await extractAudio(args.videoPath, audioPath);
  const audio = await readFile(audioPath);
  if (audio.length === 0) throw new Error("Extracted audio was empty");
  const transcriptOut = await callGemini(args.apiKey, [
    { text: AUDIO_TRANSCRIPTION_PROMPT },
    { inlineData: { mimeType: "audio/mpeg", data: audio.toString("base64") } },
  ]);
  const transcript = transcriptOut.text.trim();
  const moderated = await moderateText(args.apiKey, transcript);
  return {
    scores: moderated.scores,
    transcript,
    skipped: false,
  };
}

function mediaKeyFromPublicUrl(url: string): string | null {
  try {
    return new URL(url).pathname
      .replace(/^\/+/, "")
      .split("/")
      .map((part) => decodeURIComponent(part))
      .join("/");
  } catch {
    return null;
  }
}

async function bodyToBuffer(body: unknown): Promise<Buffer> {
  const b = body as { transformToByteArray?: () => Promise<Uint8Array> };
  if (typeof b?.transformToByteArray === "function") {
    return Buffer.from(await b.transformToByteArray());
  }
  throw new Error("S3 object body is not readable");
}

export async function fetchVideoBuffer(
  url: string,
  storageRegion?: string,
): Promise<Buffer> {
  try {
    const resp = await fetch(url);
    if (resp.ok) {
      const buf = Buffer.from(await resp.arrayBuffer());
      if (buf.length > 0) return buf;
    }
  } catch {
    // Fall through to S3 fetch.
  }
  const key = mediaKeyFromPublicUrl(url);
  if (!key) throw new Error("Could not parse video key from URL");
  const targets = getUploadTargets();
  const target =
    (storageRegion
      ? targets.find((t) => t.region === storageRegion)
      : undefined) ?? targets[0];
  if (!target)
    throw new Error("No upload bucket target available for video moderation");
  const out = await getS3ClientForRegion(target.region).send(
    new GetObjectCommand({ Bucket: target.bucket, Key: key }),
  );
  return bodyToBuffer(out.Body);
}

// ---------------------------------------------------------------------------
// Video reasoning engine
// Runs AFTER the scoring pass. Detection (scores) stays unchanged; this layer
// only adds structured, timestamped explanations for flagged content.
// ---------------------------------------------------------------------------

/** Minimum violation score for a frame to be included in reasoning. */
const REASONING_FLAG_THRESHOLD = 0.35;

/** Maximum gap (seconds) between flagged frames to still merge into one segment. */
const SEGMENT_GAP_SEC = 3.0;

type ScoredFrame = ModerationScores & {
  frameIndex: number;
  timestampSec: number;
  provider: string;
  reason?: string;
  detectedLabels?: string[];
  userSummary?: string;
  reasonInternal?: string;
};

type FrameGroup = {
  frames: ScoredFrame[];
  category: FlaggedSegment["category"];
  peakScore: number;
  startTime: number;
  endTime: number;
};

function dominantCategory(
  s: ModerationScores,
): FlaggedSegment["category"] | null {
  const entries: Array<[FlaggedSegment["category"], number]> = [
    ["hate", s.hate],
    ["sexual", s.sexual],
    ["nudity", s.nudity],
    ["violence", s.violence],
    ["suggestive", s.suggestive],
    ["spam", s.spam],
  ];
  const [cat, score] = entries.sort((a, b) => b[1] - a[1])[0];
  return score >= REASONING_FLAG_THRESHOLD ? cat : null;
}

/**
 * Groups flagged frames into contiguous time segments.
 * Frames within SEGMENT_GAP_SEC of each other with the same dominant
 * category are merged into one segment.
 */
function groupFramesIntoSegments(frames: ScoredFrame[]): FrameGroup[] {
  const flagged = frames.filter((f) => {
    const maxViol = Math.max(
      f.nudity,
      f.sexual,
      f.suggestive,
      f.violence,
      f.hate,
      f.spam,
    );
    return maxViol >= REASONING_FLAG_THRESHOLD;
  });
  if (flagged.length === 0) return [];

  const groups: FrameGroup[] = [];
  let current: FrameGroup | null = null;

  for (const frame of [...flagged].sort(
    (a, b) => a.timestampSec - b.timestampSec,
  )) {
    const cat = dominantCategory(frame);
    if (!cat) continue;
    const score = Math.max(
      frame.nudity,
      frame.sexual,
      frame.suggestive,
      frame.violence,
      frame.hate,
      frame.spam,
    );

    if (
      current === null ||
      frame.timestampSec - current.endTime > SEGMENT_GAP_SEC ||
      cat !== current.category
    ) {
      if (current) groups.push(current);
      current = {
        frames: [frame],
        category: cat,
        peakScore: score,
        startTime: frame.timestampSec,
        endTime: frame.timestampSec,
      };
    } else {
      current.frames.push(frame);
      current.endTime = frame.timestampSec;
      if (score > current.peakScore) current.peakScore = score;
    }
  }
  if (current) groups.push(current);
  return groups;
}

const VIDEO_REASONING_PROMPT = `You are an expert content safety analyst reviewing video frames.

Your task: produce a DETAILED, EVIDENCE-BASED explanation for each flagged segment.

RULES:
- Only describe what is VISUALLY PRESENT. Never invent or assume intent.
- Never use generic terms like "nudity" or "violence" alone as a summary — always describe the SPECIFIC visual content.
- For violence: describe the exact action, body parts involved, objects present (weapon, blood, impact), and whether harm is visible.
- For nudity: describe which specific body areas are exposed, the framing, and whether the presentation appears sexualised.
- For suggestive: describe the specific posture, clothing state, camera angle, and context that creates the suggestive reading.
- For hate: describe the exact symbol, text, gesture, or language and where it appears in frame.
- Blood on skin = VIOLENCE context, NOT nudity. Distinguish carefully.
- If confidence is below 0.9, explain concrete visual ambiguities (motion blur, lighting, occlusion, compression).
- Keep start_time and end_time matching the segment timestamps provided in the context.

Respond with ONLY valid JSON matching this exact schema:
{
  "flagged_segments": [
    {
      "start_time": <number>,
      "end_time": <number>,
      "category": "<nudity|sexual|suggestive|violence|hate|spam>",
      "confidence": <0.0–1.0>,
      "summary": "<1–2 sentence description of specific visual content: what, where in frame, action or state>",
      "detailed_points": [
        "<visual signal 1: specific object or body part, its location in frame, action or state>",
        "<visual signal 2: what IS present AND what is NOT present that affects classification>",
        "<visual signal 3: context that increases or reduces severity>"
      ],
      "visual_context": {
        "pose_or_action": "<neutral|aggressive|suggestive|explicit|unknown>",
        "setting": "<indoor|outdoor|unknown>",
        "interaction": "<none|person-to-person|object-interaction|unknown>"
      }
    }
  ],
  "primary_label": "<nudity|sexual|suggestive|violence|hate|spam|safe>",
  "confidence": <0.0–1.0>,
  "severity": "<low|medium|high>",
  "uncertainty_notes": ["<explanation if confidence < 0.9, else empty array>"],
  "decision": "<allow|flag_for_review|restrict|remove>"
}`;

function parseCategoryField(raw: unknown): FlaggedSegment["category"] {
  const VALID: FlaggedSegment["category"][] = [
    "nudity",
    "sexual",
    "suggestive",
    "violence",
    "hate",
    "spam",
  ];
  if (typeof raw === "string" && (VALID as string[]).includes(raw))
    return raw as FlaggedSegment["category"];
  return "violence";
}

function parsePrimaryLabel(
  raw: unknown,
): VideoReasoningResult["primary_label"] {
  const VALID: VideoReasoningResult["primary_label"][] = [
    "nudity",
    "sexual",
    "suggestive",
    "violence",
    "hate",
    "spam",
    "safe",
  ];
  if (typeof raw === "string" && (VALID as string[]).includes(raw))
    return raw as VideoReasoningResult["primary_label"];
  return "safe";
}

function parseSeverity(raw: unknown): VideoReasoningResult["severity"] {
  if (raw === "low" || raw === "medium" || raw === "high") return raw;
  return "medium";
}

function parseReasoningDecision(
  raw: unknown,
): VideoReasoningResult["decision"] {
  if (
    raw === "allow" ||
    raw === "flag_for_review" ||
    raw === "restrict" ||
    raw === "remove"
  )
    return raw;
  return "flag_for_review";
}

function parsePoseOrAction(raw: unknown): VisualContext["pose_or_action"] {
  if (
    raw === "neutral" ||
    raw === "aggressive" ||
    raw === "suggestive" ||
    raw === "explicit" ||
    raw === "unknown"
  )
    return raw;
  return "unknown";
}

function parseSetting(raw: unknown): VisualContext["setting"] {
  if (raw === "indoor" || raw === "outdoor" || raw === "unknown") return raw;
  return "unknown";
}

function parseInteraction(raw: unknown): VisualContext["interaction"] {
  if (
    raw === "none" ||
    raw === "person-to-person" ||
    raw === "object-interaction" ||
    raw === "unknown"
  )
    return raw;
  return "unknown";
}

function parseVideoReasoningJson(
  raw: string,
  groups: FrameGroup[],
): VideoReasoningResult | null {
  const cleaned = raw
    .replace(/^\uFEFF/, "")
    .replace(/```json\s*/gi, "")
    .replace(/```\s*/g, "")
    .trim();
  const match = cleaned.startsWith("{")
    ? cleaned
    : cleaned.match(/\{[\s\S]*\}/)?.[0];
  if (!match) return null;
  try {
    const p = JSON.parse(match) as Record<string, unknown>;
    const rawSegments = Array.isArray(p.flagged_segments)
      ? p.flagged_segments
      : [];

    const segments: FlaggedSegment[] = (rawSegments as unknown[])
      .map((seg): FlaggedSegment | null => {
        if (!seg || typeof seg !== "object") return null;
        const s = seg as Record<string, unknown>;
        const vctx =
          s.visual_context && typeof s.visual_context === "object"
            ? (s.visual_context as Record<string, unknown>)
            : {};
        const rawPoints = Array.isArray(s.detailed_points)
          ? s.detailed_points
          : [];
        const points = (rawPoints as unknown[])
          .filter(
            (pt): pt is string =>
              typeof pt === "string" && pt.trim().length > 0,
          )
          .map((pt) => pt.trim());
        const summary =
          typeof s.summary === "string" && s.summary.trim().length > 5
            ? s.summary.trim()
            : null;
        if (!summary) return null;
        return {
          start_time:
            typeof s.start_time === "number"
              ? s.start_time
              : (groups[0]?.startTime ?? 0),
          end_time:
            typeof s.end_time === "number"
              ? s.end_time
              : (groups[0]?.endTime ?? 0),
          category: parseCategoryField(s.category),
          confidence:
            typeof s.confidence === "number"
              ? Math.max(0, Math.min(1, s.confidence))
              : 0.5,
          summary,
          detailed_points:
            points.length > 0
              ? points
              : ["No specific visual evidence described"],
          visual_context: {
            pose_or_action: parsePoseOrAction(vctx.pose_or_action),
            setting: parseSetting(vctx.setting),
            interaction: parseInteraction(vctx.interaction),
          },
        };
      })
      .filter((s): s is FlaggedSegment => s !== null);

    const uncertaintyNotes = Array.isArray(p.uncertainty_notes)
      ? (p.uncertainty_notes as unknown[])
          .filter(
            (n): n is string => typeof n === "string" && n.trim().length > 0,
          )
          .map((n) => n.trim())
      : [];

    return {
      primary_label: parsePrimaryLabel(p.primary_label),
      confidence:
        typeof p.confidence === "number"
          ? Math.max(0, Math.min(1, p.confidence))
          : 0.5,
      severity: parseSeverity(p.severity),
      flagged_segments: segments,
      uncertainty_notes: uncertaintyNotes,
      decision: parseReasoningDecision(p.decision),
      source: "gemini_reasoning",
    };
  } catch {
    return null;
  }
}

function buildSynthesisedSummary(
  category: FlaggedSegment["category"],
  startTime: number,
  endTime: number,
  labels: string[],
): string {
  const time =
    startTime === endTime
      ? `at ${startTime.toFixed(1)}s`
      : `between ${startTime.toFixed(1)}s–${endTime.toFixed(1)}s`;
  const labelCtx =
    labels.length > 0 ? ` (context: ${labels.slice(0, 3).join(", ")})` : "";
  switch (category) {
    case "nudity":
      return `Possible exposure of intimate body areas detected ${time}${labelCtx}`;
    case "sexual":
      return `Possible sexually explicit content detected ${time}${labelCtx}`;
    case "suggestive":
      return `Possible sexually suggestive framing detected ${time}${labelCtx}`;
    case "violence":
      return `Possible violent content or physical harm detected ${time}${labelCtx}`;
    case "hate":
      return `Possible hateful symbols, language, or gestures detected ${time}${labelCtx}`;
    case "spam":
      return `Possible spam or repetitive promotional content detected ${time}${labelCtx}`;
  }
}

/**
 * Fallback: synthesise a VideoReasoningResult purely from scores + labels when
 * Gemini reasoning is unavailable. Never returns null — always produces output.
 */
function synthesizeReasoningFromScores(
  groups: FrameGroup[],
  finalScores: ModerationScores,
  detectedLabels: string[],
): VideoReasoningResult {
  const segments: FlaggedSegment[] = groups.map((g) => {
    const labelList = [
      ...new Set(g.frames.flatMap((f) => f.detectedLabels ?? [])),
    ];
    return {
      start_time: g.startTime,
      end_time: g.endTime,
      category: g.category,
      confidence: g.peakScore,
      summary: buildSynthesisedSummary(
        g.category,
        g.startTime,
        g.endTime,
        labelList,
      ),
      detailed_points: [
        labelList.length > 0
          ? `Detected visual elements: ${labelList.join(", ")}`
          : "No object labels returned by classifier",
        `Peak ${g.category} confidence: ${(g.peakScore * 100).toFixed(0)}%`,
        `Covers ${g.frames.length} frame(s) from ${g.startTime.toFixed(1)}s to ${g.endTime.toFixed(1)}s`,
      ],
      visual_context: {
        pose_or_action: "unknown",
        setting: "unknown",
        interaction: "unknown",
      },
    };
  });

  const dominantGroup = [...groups].sort(
    (a, b) => b.peakScore - a.peakScore,
  )[0];
  const primaryLabel = dominantGroup ? dominantGroup.category : "safe";
  const confidence = dominantGroup?.peakScore ?? 0;

  return {
    primary_label: primaryLabel,
    confidence,
    severity: confidence >= 0.8 ? "high" : confidence >= 0.5 ? "medium" : "low",
    flagged_segments: segments,
    uncertainty_notes:
      detectedLabels.length > 0
        ? [
            `Score-based reasoning only — detected context signals: ${detectedLabels.join(", ")}`,
          ]
        : ["Score-based reasoning only — detailed visual analysis unavailable"],
    decision: confidence >= 0.8 ? "restrict" : "flag_for_review",
    source: "score_synthesis",
  };
}

/**
 * Runs the reasoning pass after scoring.
 *
 * Groups flagged frames into time segments, sends the best representative
 * frame(s) from each segment back to Gemini with an evidence-focused prompt,
 * and returns structured, timestamped explanations.
 *
 * Detection scores are NOT modified — this layer is purely for explaining
 * what the system saw, not for changing the block/allow decision.
 *
 * Returns undefined when no frames are flagged (content is safe).
 * Falls back to synthesizeReasoningFromScores on Gemini failure.
 */
async function generateVideoReasoning(args: {
  apiKey: string;
  frameScores: ScoredFrame[];
  finalScores: ModerationScores;
  detectedLabels: string[];
  workDir: string;
}): Promise<VideoReasoningResult | undefined> {
  const groups = groupFramesIntoSegments(args.frameScores);
  if (groups.length === 0) return undefined;

  // Pick the highest-violation frame from each segment (cap at 6 to stay within token budget)
  const representativeFrames = groups.slice(0, 6).map((g) =>
    g.frames.reduce((best, f) => {
      const bScore = Math.max(
        best.nudity,
        best.sexual,
        best.suggestive,
        best.violence,
        best.hate,
      );
      const fScore = Math.max(
        f.nudity,
        f.sexual,
        f.suggestive,
        f.violence,
        f.hate,
      );
      return fScore > bScore ? f : best;
    }),
  );

  const contextLines = [
    `Video analysis context:`,
    `Total frames analyzed: ${args.frameScores.length}`,
    `Flagged segments (${groups.length}):`,
    ...groups.map(
      (g, i) =>
        `  Segment ${i + 1}: ${g.category} from ${g.startTime.toFixed(1)}s to ${g.endTime.toFixed(1)}s — peak confidence ${(g.peakScore * 100).toFixed(0)}%`,
    ),
    `All detected object/context labels: ${args.detectedLabels.join(", ") || "none"}`,
    ``,
    `Analyze the attached frame images and describe exactly what you see for each segment.`,
    `Use the timestamps above verbatim in start_time and end_time fields.`,
  ];

  const imageParts: Array<Record<string, unknown>> = [];
  for (const frame of representativeFrames) {
    const framePath = join(
      args.workDir,
      `frame-${String(frame.frameIndex).padStart(2, "0")}.jpg`,
    );
    try {
      const bytes = await readFile(framePath);
      if (bytes.length >= 500) {
        const cat = dominantCategory(frame) ?? "flagged";
        imageParts.push({
          inlineData: {
            mimeType: "image/jpeg",
            data: bytes.toString("base64"),
          },
        });
        imageParts.push({
          text: `[Frame at ${frame.timestampSec.toFixed(1)}s — ${cat} — confidence ${(Math.max(frame.nudity, frame.sexual, frame.suggestive, frame.violence, frame.hate) * 100).toFixed(0)}%]`,
        });
      }
    } catch {
      // Frame may have been cleaned up; skip it
    }
  }

  // If we couldn't load any frames, fall back to score synthesis
  if (imageParts.length === 0) {
    return synthesizeReasoningFromScores(
      groups,
      args.finalScores,
      args.detectedLabels,
    );
  }

  const parts: Array<Record<string, unknown>> = [
    { text: VIDEO_REASONING_PROMPT },
    { text: contextLines.join("\n") },
    ...imageParts,
  ];

  try {
    const out = await callGemini(args.apiKey, parts, "application/json");
    if (out.safetyBlocked) {
      return synthesizeReasoningFromScores(
        groups,
        args.finalScores,
        args.detectedLabels,
      );
    }
    const parsed = parseVideoReasoningJson(out.text, groups);
    return (
      parsed ??
      synthesizeReasoningFromScores(
        groups,
        args.finalScores,
        args.detectedLabels,
      )
    );
  } catch {
    return synthesizeReasoningFromScores(
      groups,
      args.finalScores,
      args.detectedLabels,
    );
  }
}

export async function moderateVideoMedia(args: {
  apiKey: string;
  mediaIndex: number;
  displayUrl: string;
  displayStorageRegion?: string;
  durationMs?: number;
  hasAudioTrack?: boolean;
  trustTier: ModerationTrustTier;
}): Promise<VideoModerationResult> {
  const start = Date.now();
  const workDir = join(
    tmpdir(),
    `vibo-video-mod-${Date.now()}-${randomUUID()}`,
  );
  const failures: string[] = [];
  await mkdir(workDir, { recursive: true });
  try {
    const video = await fetchVideoBuffer(
      args.displayUrl,
      args.displayStorageRegion,
    );
    if (video.length === 0) throw new Error("Downloaded video was empty");
    const mediaHash = createHash("sha256")
      .update(video.subarray(0, Math.min(video.length, 1024 * 1024)))
      .update(String(video.length))
      .digest("hex");
    const videoPath = join(workDir, "source.mp4");
    await writeFile(videoPath, video);

    const durationSec = args.durationMs ? args.durationMs / 1000 : undefined;
    const skipDeepAnalysis = (durationSec ?? 0) > 120;
    const requested = sampleCount(durationSec, args.trustTier);
    const frames = await extractFramesFromVideo({
      videoPath,
      workDir,
      durationSec,
      trustTier: args.trustTier,
    });

    // For very long videos (>120s), only analyze the first valid frame
    // (thumbnail-only mode) to avoid Gemini 400 errors on corrupted frames.
    const framesToAnalyze = skipDeepAnalysis ? frames.slice(0, 1) : frames;
    if (frames.length === 0) {
      console.warn(
        "[VideoModeration] No frames extracted, returning safe pass",
      );
      return {
        scores: { ...SAFE_PASS_SCORES },
        mediaHash,
        classificationFailed: true,
        safetyBlocked: false,
        detectedLabels: [],
        audit: {
          mediaIndex: args.mediaIndex,
          frameCountRequested: requested,
          framesAnalyzed: 0,
          frameScores: [],
          provider: "fail_safe",
          usedRekognition: false,
          failures: ["no_frames_extracted"],
          durationMs: Date.now() - start,
        },
      };
    }

    const frameScores: VideoModerationAudit["frameScores"] = [];
    let classificationFailed = false;
    let safetyBlocked = false;
    let safetyBlockReason: string | undefined;
    let safetyBlockCategory: string | undefined;
    const allDetectedLabels = new Set<string>();
    let bestAiReason: string | undefined;
    for (const frame of framesToAnalyze) {
      const score = await moderateFrame({
        apiKey: args.apiKey,
        framePath: frame.path,
        frameIndex: frame.index,
        timestampSec: frame.timestampSec,
      });
      if (score.classificationFailed) classificationFailed = true;
      if (score.safetyBlocked) {
        safetyBlocked = true;
        safetyBlockReason ??= score.safetyBlockReason;
        safetyBlockCategory ??= score.safetyBlockCategory;
      }
      for (const label of score.detectedLabels ?? []) {
        allDetectedLabels.add(label);
      }
      if (
        !bestAiReason &&
        score.reason &&
        !/error|timed out/i.test(score.reason)
      ) {
        bestAiReason = score.reason;
      }
      frameScores.push(score);
    }

    let audioTranscript: string | undefined;
    let audioScores: ModerationScores | undefined;
    if (!skipDeepAnalysis) {
      try {
        const audio = await moderateAudio({
          apiKey: args.apiKey,
          videoPath,
          workDir,
          hasAudioTrack: args.hasAudioTrack,
        });
        if (!audio.skipped) {
          audioTranscript = audio.transcript;
          audioScores = audio.scores;
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        failures.push(`audio:${msg}`);
        classificationFailed = true;
        audioScores = { ...SAFE_PASS_SCORES };
      }
    }

    const mergedLabels = [...allDetectedLabels];
    const finalScores = applyContextSignals(
      mergeScores([
        ...frameScores.map((s) => s as ModerationScores),
        ...(audioScores ? [audioScores] : []),
      ]) as ParsedModeration,
      mergedLabels,
    );

    // Reasoning pass — runs after scoring, does NOT change scores.
    // Only fires when at least one frame exceeded the flag threshold.
    // Errors are caught internally; reasoning failure never blocks the result.
    // Skipped for very long videos (>120s) to avoid Gemini failures.
    let reasoning: VideoReasoningResult | undefined;
    if (!skipDeepAnalysis) {
      try {
        reasoning = await generateVideoReasoning({
          apiKey: args.apiKey,
          frameScores: frameScores as ScoredFrame[],
          finalScores,
          detectedLabels: mergedLabels,
          workDir,
        });
      } catch {
        // Reasoning is best-effort; scoring result is always returned.
      }
    }

    const usedRekognition = frameScores.some((s) =>
      s.provider.includes("rekognition"),
    );

    console.log("VIDEO MOD DEBUG:", {
      framesAnalyzed: frameScores.length,
      frameResults: frameScores.map((f) => ({
        frame: f.frameIndex,
        time: f.timestampSec,
        provider: f.provider,
        primaryCategory: (f as ParsedModeration).primaryCategory ?? null,
        confidence: (f as ParsedModeration).confidence ?? 0,
        evidence: (f as ParsedModeration).evidence ?? [],
        nudity: f.nudity,
        violence: f.violence,
        sexual: f.sexual,
      })),
      final: {
        nudity: finalScores.nudity,
        sexual: finalScores.sexual,
        violence: finalScores.violence,
        hate: finalScores.hate,
        safe: finalScores.safe,
      },
      flagged: classificationFailed ? "fail_safe" : "scored",
    });
    const provider = [
      "gemini",
      usedRekognition ? "rekognition" : null,
      audioScores ? "audio" : null,
      failures.length ? "fail_closed" : null,
    ]
      .filter(Boolean)
      .join("+");
    return {
      scores: finalScores,
      mediaHash,
      classificationFailed,
      safetyBlocked,
      safetyBlockReason,
      safetyBlockCategory,
      detectedLabels: mergedLabels,
      aiReason: reasoning?.flagged_segments[0]?.summary ?? bestAiReason,
      reasoning,
      audit: {
        mediaIndex: args.mediaIndex,
        frameCountRequested: requested,
        framesAnalyzed: frameScores.length,
        frameScores,
        audioTranscript,
        audioScores,
        provider,
        usedRekognition,
        failures,
        durationMs: Date.now() - start,
        reasoning,
      },
    };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    failures.push(msg);
    return {
      scores: { ...SAFE_PASS_SCORES },
      classificationFailed: true,
      safetyBlocked: false,
      detectedLabels: [],
      audit: {
        mediaIndex: args.mediaIndex,
        frameCountRequested: sampleCount(
          args.durationMs ? args.durationMs / 1000 : undefined,
          args.trustTier,
        ),
        framesAnalyzed: 0,
        frameScores: [],
        provider: "fail_closed",
        usedRekognition: false,
        failures,
        durationMs: Date.now() - start,
      },
    };
  } finally {
    await rm(workDir, { recursive: true, force: true }).catch(() => {});
  }
}
